/* Country data for the flag game.
 * Codes are ISO 3166-1 alpha-2, lowercased to match flagcdn.com paths.
 * Regions drive both the region filter and hard-mode distractor picking. */

const COUNTRY_DATA = {
  Africa: [
    ['Algeria', 'dz'],
    ['Angola', 'ao'],
    ['Benin', 'bj'],
    ['Botswana', 'bw'],
    ['Burkina Faso', 'bf'],
    ['Burundi', 'bi'],
    ['Cameroon', 'cm'],
    ['Cape Verde', 'cv'],
    ['Central African Republic', 'cf'],
    ['Chad', 'td'],
    ['Comoros', 'km'],
    ['Democratic Republic of the Congo', 'cd'],
    ['Djibouti', 'dj'],
    ['Egypt', 'eg'],
    ['Equatorial Guinea', 'gq'],
    ['Eritrea', 'er'],
    ['Eswatini', 'sz'],
    ['Ethiopia', 'et'],
    ['Gabon', 'ga'],
    ['Ghana', 'gh'],
    ['Guinea', 'gn'],
    ['Guinea-Bissau', 'gw'],
    ['Ivory Coast', 'ci'],
    ['Kenya', 'ke'],
    ['Lesotho', 'ls'],
    ['Liberia', 'lr'],
    ['Libya', 'ly'],
    ['Madagascar', 'mg'],
    ['Malawi', 'mw'],
    ['Mali', 'ml'],
    ['Mauritania', 'mr'],
    ['Mauritius', 'mu'],
    ['Morocco', 'ma'],
    ['Mozambique', 'mz'],
    ['Namibia', 'na'],
    ['Niger', 'ne'],
    ['Nigeria', 'ng'],
    ['Republic of the Congo', 'cg'],
    ['Rwanda', 'rw'],
    ['Sao Tome and Principe', 'st'],
    ['Senegal', 'sn'],
    ['Seychelles', 'sc'],
    ['Sierra Leone', 'sl'],
    ['Somalia', 'so'],
    ['South Africa', 'za'],
    ['South Sudan', 'ss'],
    ['Sudan', 'sd'],
    ['Tanzania', 'tz'],
    ['The Gambia', 'gm'],
    ['Togo', 'tg'],
    ['Tunisia', 'tn'],
    ['Uganda', 'ug'],
    ['Zambia', 'zm'],
    ['Zimbabwe', 'zw'],
  ],
  Americas: [
    ['Antigua and Barbuda', 'ag'],
    ['Argentina', 'ar'],
    ['Bahamas', 'bs'],
    ['Barbados', 'bb'],
    ['Belize', 'bz'],
    ['Bolivia', 'bo'],
    ['Brazil', 'br'],
    ['Canada', 'ca'],
    ['Chile', 'cl'],
    ['Colombia', 'co'],
    ['Costa Rica', 'cr'],
    ['Cuba', 'cu'],
    ['Dominica', 'dm'],
    ['Dominican Republic', 'do'],
    ['Ecuador', 'ec'],
    ['El Salvador', 'sv'],
    ['Grenada', 'gd'],
    ['Guatemala', 'gt'],
    ['Guyana', 'gy'],
    ['Haiti', 'ht'],
    ['Honduras', 'hn'],
    ['Jamaica', 'jm'],
    ['Mexico', 'mx'],
    ['Nicaragua', 'ni'],
    ['Panama', 'pa'],
    ['Paraguay', 'py'],
    ['Peru', 'pe'],
    ['Saint Kitts and Nevis', 'kn'],
    ['Saint Lucia', 'lc'],
    ['Saint Vincent and the Grenadines', 'vc'],
    ['Suriname', 'sr'],
    ['Trinidad and Tobago', 'tt'],
    ['United States', 'us'],
    ['Uruguay', 'uy'],
    ['Venezuela', 've'],
  ],
  Asia: [
    ['Afghanistan', 'af'],
    ['Armenia', 'am'],
    ['Azerbaijan', 'az'],
    ['Bahrain', 'bh'],
    ['Bangladesh', 'bd'],
    ['Bhutan', 'bt'],
    ['Brunei', 'bn'],
    ['Cambodia', 'kh'],
    ['China', 'cn'],
    ['Cyprus', 'cy'],
    ['Georgia', 'ge'],
    ['India', 'in'],
    ['Indonesia', 'id'],
    ['Iran', 'ir'],
    ['Iraq', 'iq'],
    ['Israel', 'il'],
    ['Japan', 'jp'],
    ['Jordan', 'jo'],
    ['Kazakhstan', 'kz'],
    ['Kuwait', 'kw'],
    ['Kyrgyzstan', 'kg'],
    ['Laos', 'la'],
    ['Lebanon', 'lb'],
    ['Malaysia', 'my'],
    ['Maldives', 'mv'],
    ['Mongolia', 'mn'],
    ['Myanmar', 'mm'],
    ['Nepal', 'np'],
    ['North Korea', 'kp'],
    ['Oman', 'om'],
    ['Pakistan', 'pk'],
    ['Palestine', 'ps'],
    ['Philippines', 'ph'],
    ['Qatar', 'qa'],
    ['Saudi Arabia', 'sa'],
    ['Singapore', 'sg'],
    ['South Korea', 'kr'],
    ['Sri Lanka', 'lk'],
    ['Syria', 'sy'],
    ['Taiwan', 'tw'],
    ['Tajikistan', 'tj'],
    ['Thailand', 'th'],
    ['Timor-Leste', 'tl'],
    ['Turkey', 'tr'],
    ['Turkmenistan', 'tm'],
    ['United Arab Emirates', 'ae'],
    ['Uzbekistan', 'uz'],
    ['Vietnam', 'vn'],
    ['Yemen', 'ye'],
  ],
  Europe: [
    ['Albania', 'al'],
    ['Andorra', 'ad'],
    ['Austria', 'at'],
    ['Belarus', 'by'],
    ['Belgium', 'be'],
    ['Bosnia and Herzegovina', 'ba'],
    ['Bulgaria', 'bg'],
    ['Croatia', 'hr'],
    ['Czechia', 'cz'],
    ['Denmark', 'dk'],
    ['Estonia', 'ee'],
    ['Finland', 'fi'],
    ['France', 'fr'],
    ['Germany', 'de'],
    ['Greece', 'gr'],
    ['Hungary', 'hu'],
    ['Iceland', 'is'],
    ['Ireland', 'ie'],
    ['Italy', 'it'],
    ['Kosovo', 'xk'],
    ['Latvia', 'lv'],
    ['Liechtenstein', 'li'],
    ['Lithuania', 'lt'],
    ['Luxembourg', 'lu'],
    ['Malta', 'mt'],
    ['Moldova', 'md'],
    ['Monaco', 'mc'],
    ['Montenegro', 'me'],
    ['Netherlands', 'nl'],
    ['North Macedonia', 'mk'],
    ['Norway', 'no'],
    ['Poland', 'pl'],
    ['Portugal', 'pt'],
    ['Romania', 'ro'],
    ['Russia', 'ru'],
    ['San Marino', 'sm'],
    ['Serbia', 'rs'],
    ['Slovakia', 'sk'],
    ['Slovenia', 'si'],
    ['Spain', 'es'],
    ['Sweden', 'se'],
    ['Switzerland', 'ch'],
    ['Ukraine', 'ua'],
    ['United Kingdom', 'gb'],
    ['Vatican City', 'va'],
  ],
  Oceania: [
    ['Australia', 'au'],
    ['Fiji', 'fj'],
    ['Kiribati', 'ki'],
    ['Marshall Islands', 'mh'],
    ['Micronesia', 'fm'],
    ['Nauru', 'nr'],
    ['New Zealand', 'nz'],
    ['Palau', 'pw'],
    ['Papua New Guinea', 'pg'],
    ['Samoa', 'ws'],
    ['Solomon Islands', 'sb'],
    ['Tonga', 'to'],
    ['Tuvalu', 'tv'],
    ['Vanuatu', 'vu'],
  ],
};

const REGIONS = Object.keys(COUNTRY_DATA);

const COUNTRIES = REGIONS.flatMap((region) =>
  COUNTRY_DATA[region].map(([name, code]) => ({ name, code, region }))
);
