/* Languages for the script recognition game.
 *
 * Samples are the kind of text that ends up on a street sign, a shopfront or a
 * road marking, because that is all you ever get to read in a round. `tells`
 * names the letters and habits that give the language away, and is shown after
 * you answer: that part is what actually transfers to play.
 *
 *   id          stable key, also used for repetition weights
 *   script      picks the font stack in styles.css
 *   dir         'rtl' where the script runs right to left
 *   countries   ISO 3166-1 alpha-2 codes, lowercase, matching js/countries.js
 *   confusable  ids hard mode prefers as wrong answers
 */

const LANGUAGES = [
  /* ---------- Latin, central and eastern Europe ---------- */
  {
    id: 'pl',
    name: 'Polish',
    script: 'latin',
    countries: ['pl'],
    tells: 'ł ż ś ć ń ą ę, and the digraphs sz, cz, rz. The slashed ł is the giveaway; no other Slavic language uses it.',
    samples: ['Wjazd tylko dla mieszkańców', 'Sklep spożywczy', 'Zakaz wstępu', 'Uwaga, wyjazd samochodów', 'ul. Kościuszki'],
    confusable: ['cs', 'sk', 'sl', 'hr'],
  },
  {
    id: 'cs',
    name: 'Czech',
    script: 'latin',
    countries: ['cz'],
    tells: 'ř and ů belong to Czech alone. Also ě, and á é í ó ú ý on top of the háček letters.',
    samples: ['Vjezd zakázán', 'Potraviny', 'Pozor, vlak!', 'Otevřeno denně', 'Náměstí Míru'],
    confusable: ['sk', 'pl', 'sl', 'hr'],
  },
  {
    id: 'sk',
    name: 'Slovak',
    script: 'latin',
    countries: ['sk'],
    tells: 'Looks like Czech but swaps ř and ů for ô, ä and the long ľ, ĺ, ŕ.',
    samples: ['Vstup zakázaný', 'Potraviny', 'Otvorené', 'Pozor, pes', 'Námestie slobody'],
    confusable: ['cs', 'pl', 'sl', 'hr'],
  },
  {
    id: 'sl',
    name: 'Slovene',
    script: 'latin',
    countries: ['si'],
    tells: 'Only č, š and ž — no acutes at all. Heavy on j, and words ending in -išče or -ost.',
    samples: ['Vstop prepovedan', 'Trgovina', 'Odprto', 'Prepovedano parkiranje', 'Gostilna pri mostu'],
    confusable: ['hr', 'sk', 'cs', 'pl'],
  },
  {
    id: 'hr',
    name: 'Croatian / Bosnian',
    script: 'latin',
    countries: ['hr', 'ba', 'me'],
    tells: 'č, ć, đ, š, ž. The ć and đ separate it from Slovene, and -ije- turns up where Serbian writes -e-.',
    samples: ['Zabranjen ulaz', 'Ljekarna', 'Radno vrijeme', 'Pekara', 'Zabranjeno parkiranje'],
    confusable: ['sl', 'sk', 'cs', 'sq'],
  },
  {
    id: 'hu',
    name: 'Hungarian',
    script: 'latin',
    countries: ['hu'],
    tells: 'The double acutes ő and ű exist almost nowhere else, and gy, ny, sz, zs, cs cluster everywhere.',
    samples: ['Belépni tilos', 'Gyógyszertár', 'Nyitva', 'Behajtani tilos', 'Kossuth Lajos utca'],
    confusable: ['sk', 'ro', 'cs', 'pl'],
  },
  {
    id: 'ro',
    name: 'Romanian',
    script: 'latin',
    countries: ['ro', 'md'],
    tells: 'ă, â and î, plus comma-below ș and ț. A Romance language sitting in a Slavic neighbourhood.',
    samples: ['Intrarea interzisă', 'Farmacie', 'Deschis', 'Strada Mihai Viteazul', 'Atenție la tren'],
    confusable: ['hu', 'it', 'sq', 'pl'],
  },
  {
    id: 'sq',
    name: 'Albanian',
    script: 'latin',
    countries: ['al', 'xk'],
    tells: 'Only ë and ç as accents, but ë is everywhere, often at the end of a word. Watch for sh, xh, gj, ll, rr.',
    samples: ['Ndalohet hyrja', 'Farmaci', 'Hapur', 'Rruga e Dibrës', 'Ndalohet parkimi'],
    confusable: ['hr', 'ro', 'tr', 'sl'],
  },
  {
    id: 'lt',
    name: 'Lithuanian',
    script: 'latin',
    countries: ['lt'],
    tells: 'ė, į, ų, ū alongside č, š, ž. Nouns end in -as, -is or -us far more often than not.',
    samples: ['Įėjimas draudžiamas', 'Vaistinė', 'Atidaryta', 'Gedimino gatvė', 'Eismas draudžiamas'],
    confusable: ['lv', 'et', 'pl', 'fi'],
  },
  {
    id: 'lv',
    name: 'Latvian',
    script: 'latin',
    countries: ['lv'],
    tells: 'Macrons ā, ē, ī, ū and the cedilla letters ģ, ķ, ļ, ņ. Almost every masculine noun ends in -s.',
    samples: ['Ieeja aizliegta', 'Aptieka', 'Atvērts', 'Brīvības iela', 'Stāvēt aizliegts'],
    confusable: ['lt', 'et', 'fi', 'pl'],
  },
  {
    id: 'et',
    name: 'Estonian',
    script: 'latin',
    countries: ['ee'],
    tells: 'õ next to ä, ö, ü, and doubled vowels like aa and ee. No š or ž in ordinary words.',
    samples: ['Sissepääs keelatud', 'Apteek', 'Avatud', 'Narva maantee', 'Parkimine keelatud'],
    confusable: ['fi', 'lv', 'lt', 'sv'],
  },
  {
    id: 'fi',
    name: 'Finnish',
    script: 'latin',
    countries: ['fi'],
    tells: 'ä and ö but never õ, doubled consonants and vowels everywhere, and almost no b, c, f or z.',
    samples: ['Sisäänkäynti kielletty', 'Apteekki', 'Avoinna', 'Mannerheimintie', 'Pysäköinti kielletty'],
    confusable: ['et', 'sv', 'lv', 'lt'],
  },

  /* ---------- Nordic ---------- */
  {
    id: 'sv',
    name: 'Swedish',
    script: 'latin',
    countries: ['se'],
    tells: 'å, ä, ö. The ä and ö are what separate it from Norwegian and Danish, which use æ and ø.',
    samples: ['Infart förbjuden', 'Apotek', 'Öppet', 'Drottninggatan', 'Parkering förbjuden'],
    confusable: ['no', 'da', 'fi', 'de'],
  },
  {
    id: 'no',
    name: 'Norwegian',
    script: 'latin',
    countries: ['no'],
    tells: 'æ, ø, å like Danish. Norwegian writes gate and vei for streets, and prefers av where Danish writes af.',
    samples: ['Innkjøring forbudt', 'Apotek', 'Åpent', 'Karl Johans gate', 'Parkering forbudt'],
    confusable: ['da', 'sv', 'is', 'fi'],
  },
  {
    id: 'da',
    name: 'Danish',
    script: 'latin',
    countries: ['dk'],
    tells: 'æ, ø, å like Norwegian. Danish streets are gade or vej, and -else endings are common.',
    samples: ['Indkørsel forbudt', 'Apotek', 'Åbent', 'Nørregade', 'Parkering forbudt'],
    confusable: ['no', 'sv', 'is', 'de'],
  },
  {
    id: 'is',
    name: 'Icelandic',
    script: 'latin',
    countries: ['is'],
    tells: 'ð and þ appear in no other living language written in Latin script. Also æ and every vowel with an acute.',
    samples: ['Aðgangur bannaður', 'Apótek', 'Opið', 'Laugavegur', 'Bannað að leggja'],
    confusable: ['no', 'da', 'sv', 'fi'],
  },

  /* ---------- Western Europe ---------- */
  {
    id: 'de',
    name: 'German',
    script: 'latin',
    countries: ['de', 'at', 'ch', 'li'],
    tells: 'ß plus ä, ö, ü, and every noun capitalised mid-sentence. Swiss German writing drops the ß for ss.',
    samples: ['Einfahrt freihalten', 'Apotheke', 'Geöffnet', 'Bahnhofstraße', 'Parken verboten'],
    confusable: ['nl', 'da', 'sv', 'af'],
  },
  {
    id: 'nl',
    name: 'Dutch',
    script: 'latin',
    countries: ['nl', 'be', 'sr'],
    tells: 'The ij pair, doubled vowels aa, ee, oo, uu, and no accents to speak of. Words end in -straat and -weg.',
    samples: ['Verboden toegang', 'Apotheek', 'Geopend', 'Uitrit vrijhouden', 'Kerkstraat'],
    confusable: ['af', 'de', 'da', 'sv'],
  },
  {
    id: 'af',
    name: 'Afrikaans',
    script: 'latin',
    countries: ['za', 'na'],
    tells: 'Dutch-looking but shorter, with y where Dutch writes ij, and ê or ô turning up. Straat and Weg on signs.',
    samples: ['Geen toegang', 'Apteek', 'Oop', 'Kerkstraat', 'Geen parkering'],
    confusable: ['nl', 'de', 'da', 'sv'],
  },
  {
    id: 'fr',
    name: 'French',
    script: 'latin',
    countries: ['fr', 'be', 'ch', 'lu', 'mc', 'sn', 'ci', 'ml', 'bf', 'ne', 'td', 'cd', 'cg', 'ga', 'bj', 'tg', 'gn', 'ht'],
    tells: 'é è ê and the cedilla ç, with de, la and les binding words together. Rue and Avenue on street signs.',
    samples: ['Entrée interdite', 'Pharmacie', 'Ouvert', 'Rue de la Gare', 'Stationnement interdit'],
    confusable: ['it', 'ca', 'pt', 'es'],
  },
  {
    id: 'es',
    name: 'Spanish',
    script: 'latin',
    countries: ['es', 'mx', 'ar', 'co', 'pe', 'cl', 've', 'ec', 'bo', 'py', 'uy', 'gt', 'hn', 'sv', 'ni', 'cr', 'pa', 'cu', 'do', 'gq'],
    tells: 'ñ and the upside-down ¿ and ¡. Only á é í ó ú for accents, never à or ã.',
    samples: ['Prohibido el paso', 'Farmacia', 'Abierto', 'Calle Mayor', 'Prohibido estacionar'],
    confusable: ['pt', 'ptbr', 'it', 'ca'],
  },
  {
    id: 'pt',
    name: 'Portuguese (Portugal)',
    script: 'latin',
    countries: ['pt'],
    tells: 'ã and õ, plus ç and the à. European Portuguese keeps autocarro, comboio and casa de banho where Brazil does not.',
    samples: ['Entrada proibida', 'Farmácia', 'Aberto', 'Rua da Liberdade', 'Estacionamento proibido'],
    confusable: ['ptbr', 'es', 'ca', 'fr'],
  },
  {
    id: 'ptbr',
    name: 'Portuguese (Brazil)',
    script: 'latin',
    countries: ['br'],
    tells: 'Same letters as Portugal, different words: ônibus not autocarro, trem not comboio, banheiro not casa de banho.',
    samples: ['Proibido estacionar', 'Farmácia', 'Ponto de ônibus', 'Rua das Flores', 'Banheiro'],
    confusable: ['pt', 'es', 'ca', 'it'],
  },
  {
    id: 'it',
    name: 'Italian',
    script: 'latin',
    countries: ['it', 'sm', 'va', 'ch'],
    tells: 'Grave accents à, è, ò at the end of words, doubled consonants, and gli and gn clusters. Via and Piazza on signs.',
    samples: ["Vietato l'ingresso", 'Farmacia', 'Aperto', 'Via Roma', 'Divieto di sosta'],
    confusable: ['es', 'pt', 'ca', 'ro'],
  },
  {
    id: 'ca',
    name: 'Catalan',
    script: 'latin',
    countries: ['ad', 'es'],
    tells: 'The middle dot in l·l is unique to Catalan. Also ny where Spanish has ñ, and Carrer for street.',
    samples: ['Prohibit el pas', 'Farmàcia', 'Obert', 'Carrer Major', 'Prohibit aparcar'],
    confusable: ['es', 'pt', 'fr', 'it'],
  },
  {
    id: 'ga',
    name: 'Irish',
    script: 'latin',
    countries: ['ie'],
    tells: 'Acute fadas á é í ó ú, silent-looking bh, mh and dh, and the hyphenated an t- prefix. Sráid means street.',
    samples: ['Ná téigh isteach', 'Oscailte', 'Sráid an Chaisleáin', 'Cosc ar pháirceáil', 'Fáilte'],
    confusable: ['cy', 'is', 'mt', 'fi'],
  },
  {
    id: 'cy',
    name: 'Welsh',
    script: 'latin',
    countries: ['gb'],
    tells: 'll, dd and ff as single sounds, w and y used as vowels, and circumflexes like ŵ and ŷ. Always beside English.',
    samples: ['Dim mynediad', 'Ar agor', 'Croeso i Gymru', 'Araf', 'Dim parcio'],
    confusable: ['ga', 'is', 'mt', 'fi'],
  },
  {
    id: 'mt',
    name: 'Maltese',
    script: 'latin',
    countries: ['mt'],
    tells: 'ħ, ġ, ż and ċ, with the article il- hyphenated onto words. Semitic grammar written in Latin letters.',
    samples: ['Ipprojbit id-dħul', 'Miftuħ', 'Triq ir-Repubblika', 'Spiżerija', 'Ipprojbit l-ipparkjar'],
    confusable: ['it', 'ga', 'sq', 'tr'],
  },
  {
    id: 'tr',
    name: 'Turkish',
    script: 'latin',
    countries: ['tr', 'cy'],
    tells: 'The dotless ı and dotted İ, plus ş, ğ, ç, ö, ü. The soft ğ never starts a word.',
    samples: ['Girilmez', 'Eczane', 'Açık', 'Atatürk Caddesi', 'Park yapılmaz'],
    confusable: ['az', 'sq', 'uz', 'mt'],
  },
  {
    id: 'az',
    name: 'Azerbaijani',
    script: 'latin',
    countries: ['az'],
    tells: 'Turkish letters plus ə, which no other language uses in normal writing. Also q and x as everyday letters.',
    samples: ['Giriş qadağandır', 'Aptek', 'Açıqdır', 'Nizami küçəsi', 'Dayanmaq qadağandır'],
    confusable: ['tr', 'uz', 'sq', 'kk'],
  },
  {
    id: 'uz',
    name: 'Uzbek',
    script: 'latin',
    countries: ['uz'],
    tells: 'The apostrophe letters oʻ and gʻ, and sh and ch written as pairs. Ends in -xona for buildings.',
    samples: ['Kirish taqiqlangan', 'Dorixona', 'Ochiq', 'Amir Temur koʻchasi', 'Toʻxtash taqiqlanadi'],
    confusable: ['az', 'tr', 'ms', 'id'],
  },

  /* ---------- Cyrillic ---------- */
  {
    id: 'ru',
    name: 'Russian',
    script: 'cyrillic',
    countries: ['ru'],
    tells: 'ы, э, ъ and ё. If you see ы you are not in Ukraine or Bulgaria.',
    samples: ['Вход запрещён', 'Аптека', 'Продукты', 'Улица Ленина', 'Осторожно, поезд'],
    confusable: ['uk', 'bg', 'be', 'sr'],
  },
  {
    id: 'uk',
    name: 'Ukrainian',
    script: 'cyrillic',
    countries: ['ua'],
    tells: 'і, ї, є and ґ, and no ы, э or ъ. The dotted і instead of и is the fastest check.',
    samples: ['Вхід заборонено', 'Аптека', 'Продукти', 'Вулиця Шевченка', 'Обережно, потяг'],
    confusable: ['ru', 'be', 'bg', 'sr'],
  },
  {
    id: 'be',
    name: 'Belarusian',
    script: 'cyrillic',
    countries: ['by'],
    tells: 'ў, the short u, appears nowhere else. Uses і like Ukrainian but never ї or є.',
    samples: ['Уваход забаронены', 'Аптэка', 'Крама', 'Вуліца Незалежнасці', 'Асцярожна'],
    confusable: ['ru', 'uk', 'bg', 'sr'],
  },
  {
    id: 'bg',
    name: 'Bulgarian',
    script: 'cyrillic',
    countries: ['bg'],
    tells: 'ъ turns up in the middle of ordinary words, and there is no ы, э or ё. Lots of щ.',
    samples: ['Вход забранен', 'Аптека', 'Работно време', 'Улица Раковски', 'Внимание'],
    confusable: ['ru', 'mk', 'sr', 'uk'],
  },
  {
    id: 'sr',
    name: 'Serbian (Cyrillic)',
    script: 'cyrillic',
    countries: ['rs', 'ba', 'me'],
    tells: 'ј, љ, њ, ђ, ћ and џ. The Latin j inside Cyrillic text is the tell, and Serbian signs often repeat in Latin.',
    samples: ['Забрањен улаз', 'Апотека', 'Радно време', 'Улица кнеза Милоша', 'Забрањено паркирање'],
    confusable: ['mk', 'bg', 'ru', 'uk'],
  },
  {
    id: 'mk',
    name: 'Macedonian',
    script: 'cyrillic',
    countries: ['mk'],
    tells: 'Serbian letters but with ѓ and ќ instead of ђ and ћ, plus ѕ. Плоштад means square.',
    samples: ['Забранет влез', 'Аптека', 'Работно време', 'Плоштад Македонија', 'Забрането паркирање'],
    confusable: ['sr', 'bg', 'ru', 'uk'],
  },
  {
    id: 'kk',
    name: 'Kazakh',
    script: 'cyrillic',
    countries: ['kz'],
    tells: 'Russian letters plus ә, ғ, қ, ң, ө, ұ, ү, һ and і. Көше means street.',
    samples: ['Кіру тыйым салынған', 'Дәріхана', 'Дүкен', 'Абай көшесі', 'Ашық'],
    confusable: ['ky', 'ru', 'mn', 'be'],
  },
  {
    id: 'ky',
    name: 'Kyrgyz',
    script: 'cyrillic',
    countries: ['kg'],
    tells: 'ң, ө and ү, but none of the Kazakh ә, қ or ғ. Көчө means street.',
    samples: ['Кирүүгө тыюу салынат', 'Дарыкана', 'Дүкөн', 'Чүй проспекти', 'Ачык'],
    confusable: ['kk', 'mn', 'ru', 'be'],
  },
  {
    id: 'mn',
    name: 'Mongolian',
    script: 'cyrillic',
    countries: ['mn'],
    tells: 'ө and ү with doubled vowels like аа and ээ, and endings in -ын or -ийн. No ә or қ.',
    samples: ['Нэвтрэхийг хориглоно', 'Эмийн сан', 'Дэлгүүр', 'Их сургуулийн гудамж', 'Нээлттэй'],
    confusable: ['ky', 'kk', 'ru', 'be'],
  },

  /* ---------- Other European and Middle Eastern scripts ---------- */
  {
    id: 'el',
    name: 'Greek',
    script: 'greek',
    countries: ['gr', 'cy'],
    tells: 'The Greek alphabet: Σ, Δ, Θ, Ω, Φ. Signs almost always repeat in Latin underneath.',
    samples: ['Απαγορεύεται η είσοδος', 'Φαρμακείο', 'Ανοιχτά', 'Οδός Ερμού', 'Απαγορεύεται η στάθμευση'],
    confusable: ['ru', 'bg', 'hy', 'ka'],
  },
  {
    id: 'hy',
    name: 'Armenian',
    script: 'armenian',
    countries: ['am'],
    tells: 'Its own alphabet, rounded with many short downstrokes and a comma-like full stop.',
    samples: ['Մուտքն արգելված է', 'Դեղատուն', 'Խանութ', 'Աբովյան փողոց', 'Բաց է'],
    confusable: ['ka', 'el', 'am', 'he'],
  },
  {
    id: 'ka',
    name: 'Georgian',
    script: 'georgian',
    countries: ['ge'],
    tells: 'Its own alphabet, all curves and loops with no capitals at all.',
    samples: ['შესვლა აკრძალულია', 'აფთიაქი', 'მაღაზია', 'რუსთაველის გამზირი', 'ღიაა'],
    confusable: ['hy', 'el', 'am', 'th'],
  },
  {
    id: 'he',
    name: 'Hebrew',
    script: 'hebrew',
    countries: ['il'],
    tells: 'Square block letters running right to left, with no ascenders or descenders to speak of.',
    samples: ['הכניסה אסורה', 'בית מרקחת', 'פתוח', 'רחוב הרצל', 'אין חניה'],
    dir: 'rtl',
    confusable: ['ar', 'fa', 'ur', 'hy'],
  },
  {
    id: 'ar',
    name: 'Arabic',
    script: 'arabic',
    countries: ['eg', 'sa', 'ma', 'dz', 'tn', 'ly', 'jo', 'sy', 'iq', 'ae', 'om', 'kw', 'qa', 'bh', 'ye', 'ps', 'lb', 'sd', 'mr'],
    tells: 'Joined right-to-left script with no p, ch, zh or g letters. If you spot پ چ ژ گ it is Persian or Urdu instead.',
    samples: ['ممنوع الدخول', 'صيدلية', 'مفتوح', 'شارع الملك فهد', 'ممنوع الوقوف'],
    dir: 'rtl',
    confusable: ['fa', 'ur', 'he', 'tr'],
  },
  {
    id: 'fa',
    name: 'Persian',
    script: 'arabic',
    countries: ['ir'],
    tells: 'Arabic script plus the four Persian letters پ, چ, ژ and گ. خیابان means street.',
    samples: ['ورود ممنوع', 'داروخانه', 'باز است', 'خیابان ولیعصر', 'پارک ممنوع'],
    dir: 'rtl',
    confusable: ['ar', 'ur', 'he'],
  },
  {
    id: 'ur',
    name: 'Urdu',
    script: 'nastaliq',
    countries: ['pk'],
    tells: 'Written in a sloping Nastaliq style that stacks downwards, with ٹ, ڈ, ڑ and the looping ہ and ے.',
    samples: ['داخلہ منع ہے', 'دواخانہ', 'کھلا ہے', 'شاہراہِ قائداعظم', 'پارکنگ منع ہے'],
    dir: 'rtl',
    confusable: ['fa', 'ar', 'he'],
  },

  /* ---------- South Asia ---------- */
  {
    id: 'hi',
    name: 'Hindi',
    script: 'devanagari',
    countries: ['in'],
    tells: 'Devanagari, hung from a continuous horizontal bar. Nepali uses the same script, so look for the country context.',
    samples: ['प्रवेश निषेध', 'दवाई की दुकान', 'खुला है', 'महात्मा गांधी मार्ग', 'पार्किंग नहीं'],
    confusable: ['ne', 'bn', 'ta', 'si'],
  },
  {
    id: 'ne',
    name: 'Nepali',
    script: 'devanagari',
    countries: ['np'],
    tells: 'Same Devanagari bar as Hindi. Nepali sentences end in छ or गर्नुहोस्, which Hindi never does.',
    samples: ['प्रवेश निषेध', 'औषधि पसल', 'खुला छ', 'दरबार मार्ग', 'कृपया पर्खनुहोस्'],
    confusable: ['hi', 'bn', 'ta', 'si'],
  },
  {
    id: 'bn',
    name: 'Bengali',
    script: 'bengali',
    countries: ['bd', 'in'],
    tells: 'A bar like Devanagari, but the letters below it are rounder and full of triangular hooks.',
    samples: ['প্রবেশ নিষেধ', 'ওষুধের দোকান', 'খোলা', 'রাস্তা বন্ধ', 'সাবধান'],
    confusable: ['hi', 'ne', 'ta', 'si'],
  },
  {
    id: 'ta',
    name: 'Tamil',
    script: 'tamil',
    countries: ['lk', 'in', 'sg'],
    tells: 'Wide, loopy letters with no connecting bar. Appears next to Sinhala in Sri Lanka and English in Singapore.',
    samples: ['உள்ளே நுழைய தடை', 'மருந்தகம்', 'திறந்திருக்கிறது', 'கடை', 'எச்சரிக்கை'],
    confusable: ['si', 'bn', 'hi', 'th'],
  },
  {
    id: 'si',
    name: 'Sinhala',
    script: 'sinhala',
    countries: ['lk'],
    tells: 'Very round, bubbly letters with curls on top. Sri Lankan signs usually carry Sinhala, Tamil and English together.',
    samples: ['ඇතුල් වීම තහනම්', 'බෙහෙත් ශාලාව', 'විවෘතයි', 'පාර', 'අවවාදයයි'],
    confusable: ['ta', 'bn', 'my', 'km'],
  },

  /* ---------- Southeast and East Asia ---------- */
  {
    id: 'th',
    name: 'Thai',
    script: 'thai',
    countries: ['th'],
    tells: 'Tall loops and no spaces between words, with tone marks floating above the line.',
    samples: ['ห้ามเข้า', 'ร้านขายยา', 'เปิด', 'ถนนสุขุมวิท', 'ห้ามจอด'],
    confusable: ['lo', 'km', 'my', 'si'],
  },
  {
    id: 'lo',
    name: 'Lao',
    script: 'lao',
    countries: ['la'],
    tells: 'Looks like a simplified, rounder Thai with fewer sharp loops and a smaller alphabet.',
    samples: ['ຫ້າມເຂົ້າ', 'ຮ້ານຂາຍຢາ', 'ເປີດ', 'ຖະໜົນ', 'ລະວັງ'],
    confusable: ['th', 'km', 'my', 'si'],
  },
  {
    id: 'km',
    name: 'Khmer',
    script: 'khmer',
    countries: ['kh'],
    tells: 'Angular letters with tall vertical strokes and marks stacked below the line as well as above.',
    samples: ['ហាមចូល', 'ឱសថស្ថាន', 'បើក', 'ផ្លូវ', 'ប្រយ័ត្ន'],
    confusable: ['th', 'lo', 'my', 'si'],
  },
  {
    id: 'my',
    name: 'Burmese',
    script: 'myanmar',
    countries: ['mm'],
    tells: 'Almost entirely circles and part-circles sitting in a row. Nothing else looks like it.',
    samples: ['မဝင်ရ', 'ဆေးဆိုင်', 'ဖွင့်သည်', 'လမ်း', 'သတိ'],
    confusable: ['km', 'th', 'lo', 'si'],
  },
  {
    id: 'vi',
    name: 'Vietnamese',
    script: 'latin',
    countries: ['vn'],
    tells: 'Latin letters carrying two marks at once, as in ế, ộ and ữ, plus the crossed đ. Words are mostly one syllable.',
    samples: ['Cấm vào', 'Nhà thuốc', 'Mở cửa', 'Đường Lê Lợi', 'Cấm đỗ xe'],
    confusable: ['id', 'ms', 'tl', 'pt'],
  },
  {
    id: 'id',
    name: 'Indonesian',
    script: 'latin',
    countries: ['id'],
    tells: 'Plain Latin with no accents, di- and ke- prefixes, and Jalan for street. Mobil means car, not kereta.',
    samples: ['Dilarang masuk', 'Apotek', 'Buka', 'Jalan Merdeka', 'Dilarang parkir'],
    confusable: ['ms', 'tl', 'vi', 'sw'],
  },
  {
    id: 'ms',
    name: 'Malay',
    script: 'latin',
    countries: ['my', 'bn', 'sg'],
    tells: 'Nearly identical to Indonesian, but kereta means car, farmasi replaces apotek, and Awas is the warning word.',
    samples: ['Dilarang meletak kereta', 'Farmasi', 'Awas! Kerja sedang dijalankan', 'Jalan Bukit Bintang', 'Kedai runcit'],
    confusable: ['id', 'tl', 'vi', 'sw'],
  },
  {
    id: 'tl',
    name: 'Filipino',
    script: 'latin',
    countries: ['ph'],
    tells: 'Bawal is the standard prohibition word, with mga and ng scattered through the text and plenty of Spanish loanwords.',
    samples: ['Bawal pumasok', 'Bukas', 'Bawal tumawid', 'Botika', 'Mag-ingat sa aso'],
    confusable: ['id', 'ms', 'es', 'vi'],
  },
  {
    id: 'ja',
    name: 'Japanese',
    script: 'japanese',
    countries: ['jp'],
    tells: 'Dense kanji mixed with the flowing hiragana の, は, り and angular katakana. The の is the quickest check.',
    samples: ['立入禁止', '駐車禁止', '営業中', '一時停止', 'この先行き止まり'],
    confusable: ['zh', 'zhtw', 'ko'],
  },
  {
    id: 'ko',
    name: 'Korean',
    script: 'korean',
    countries: ['kr', 'kp'],
    tells: 'Hangul blocks built from circles and straight lines, with lots of ㅇ and ㅁ. Nothing like Chinese characters.',
    samples: ['출입금지', '약국', '영업중', '주차금지', '어서오세요'],
    confusable: ['ja', 'zh', 'zhtw'],
  },
  {
    id: 'zh',
    name: 'Chinese (Simplified)',
    script: 'chinese',
    countries: ['cn', 'sg'],
    tells: 'Characters only, no kana. Simplified forms like 门, 车, 国 and 药 have fewer strokes than the Taiwanese ones.',
    samples: ['禁止入内', '药店', '营业中', '停车场', '前方施工'],
    confusable: ['zhtw', 'ja', 'ko'],
  },
  {
    id: 'zhtw',
    name: 'Chinese (Traditional)',
    script: 'chinese-trad',
    countries: ['tw'],
    tells: 'Same language, denser characters: 門, 車, 國 and 藥 where the mainland writes 门, 车, 国 and 药.',
    samples: ['禁止進入', '藥局', '營業中', '停車場', '前方施工'],
    confusable: ['zh', 'ja', 'ko'],
  },

  /* ---------- Africa ---------- */
  {
    id: 'sw',
    name: 'Swahili',
    script: 'latin',
    countries: ['tz', 'ke', 'ug'],
    tells: 'Prefixes ki-, wa-, ma- and m- start most nouns, vowels end almost every word, and Duka means shop.',
    samples: ['Hairuhusiwi kuingia', 'Duka la dawa', 'Imefunguliwa', 'Barabara imefungwa', 'Karibu'],
    confusable: ['zu', 'so', 'id', 'ms'],
  },
  {
    id: 'zu',
    name: 'Zulu / Xhosa',
    script: 'latin',
    countries: ['za'],
    tells: 'Clusters like hl, ngc, dl and nq, and words starting with uku- or um-. Sits beside English and Afrikaans.',
    samples: ['Akungenwa', 'Umgwaqo uvaliwe', 'Vulekile', 'Qaphela inja', 'Siyakwamukela'],
    confusable: ['sw', 'af', 'so', 'mg'],
  },
  {
    id: 'so',
    name: 'Somali',
    script: 'latin',
    countries: ['so'],
    tells: 'Doubled vowels aa, ee, oo and ii, with x, c and q used as consonants of their own.',
    samples: ['Gelitaanka waa mamnuuc', 'Farmasi', 'Waa furan', 'Waddada', 'Digniin'],
    confusable: ['sw', 'zu', 'ms', 'mg'],
  },
  {
    id: 'am',
    name: 'Amharic',
    script: 'ethiopic',
    countries: ['et'],
    tells: 'The Ge\u02bdez syllabary: boxy, upright characters, each one a whole syllable. Unmistakable once seen.',
    samples: ['መግቢያ ክልክል ነው', 'መድኃኒት ቤት', 'ክፍት ነው', 'መንገድ', 'ጥንቃቄ'],
    confusable: ['hy', 'ka', 'he', 'si'],
  },
  {
    id: 'mg',
    name: 'Malagasy',
    script: 'latin',
    countries: ['mg'],
    tells: 'Very long words full of a and o, ending in -na, -ka or -tra. French signage usually sits alongside it.',
    samples: ['Tsy azo idirana', 'Misokatra', 'Lalana mikatona', 'Fivarotana', 'Tongasoa'],
    confusable: ['sw', 'zu', 'id', 'ms'],
  },

  /* ---------- Pacific ---------- */
  {
    id: 'mi',
    name: 'Maori',
    script: 'latin',
    countries: ['nz'],
    tells: 'wh and ng as single sounds, macrons ā ē ī ō ū, and every syllable ending in a vowel. Always paired with English.',
    samples: ['Haere mai', 'Kia ora', 'Whare paku', 'Aotearoa', 'Kaua e haere'],
    confusable: ['sm', 'to', 'fj', 'mg'],
  },
  {
    id: 'sm',
    name: 'Samoan',
    script: 'latin',
    countries: ['ws'],
    tells: "The okina apostrophe inside words, macrons, and the fa'a- prefix. No wh or ng pairs the way Maori has them.",
    samples: ['Afio mai', "Fa'amolemole", 'Fale oloa', 'Faleuila', 'Manuia'],
    confusable: ['to', 'mi', 'fj', 'ms'],
  },
  {
    id: 'to',
    name: 'Tongan',
    script: 'latin',
    countries: ['to'],
    tells: 'Macrons and the okina like Samoan, but with an h where Samoan writes s, as in Mālō rather than Malo.',
    samples: ['Mālō e lelei', 'Fakamolemole', 'Fale koloa', 'Tapu', 'Faka‘apa‘apa'],
    confusable: ['sm', 'mi', 'fj', 'ms'],
  },
  {
    id: 'fj',
    name: 'Fijian',
    script: 'latin',
    countries: ['fj'],
    tells: 'No macrons or apostrophes, unlike its neighbours, and heavy on the prefixes va- and vaka-. Bula is everywhere.',
    samples: ['Bula vinaka', 'Vinaka vakalevu', 'Sitoa', 'Vale ni volavola', 'Kua ni curu'],
    confusable: ['sm', 'to', 'mi', 'ms'],
  },
];
